name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Dieser Schritt lädt den Code aus deinem GitHub-Repository herunter
      - name: Checkout code
        uses: actions/checkout@v3

      # Dieser Schritt richtet Node.js in der angegebenen Version (hier Version 16) ein,
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Abhängigkeiten installieren
      - name: Install Dependencies
        run: |
          cd app
          npm install

      # Build der Anwendung
      - name: Build the React App
        run: |
          cd app
          npm run build

      # Dieser Schritt richtet die AWS CLI ein und konfiguriert die notwendigen
      # AWS-Zugangsdaten (AWS Access Key ID und Secret Access Key) sowie die Region
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 bucket if it doesn't exist
        run: |
          if ! aws s3api head-bucket --bucket dreamsync-app-ilona; then
            echo "Bucket does not exist, creating..."
            aws s3 mb s3://dreamsync-app-ilona
          else
            echo "Bucket already exists."
          fi

        # Website-Hosting aktivieren
      - name: Enable static website hosting on S3
        run: |
          aws s3 website s3://dreamsync-app-ilona/ --index-document index.html --error-document 404.html

      # s3 Bucket Deployen
      - name: Deploy to S3
        run: |
          aws s3 sync ./app/dist/ s3://dreamsync-app-ilona --delete


    
