name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Dieser Schritt lädt den Code aus deinem GitHub-Repository herunter
      - name: Checkout code
        uses: actions/checkout@v3

      # Dieser Schritt richtet Node.js in der angegebenen Version (hier Version 16) ein,
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Abhängigkeiten installieren
      - name: Install Dependencies
        run: |
          cd app
          npm install

      # Build der Anwendung
      - name: Build the React App
        run: |
          cd app
          npm run build

      # s3 Bucket Deployen
      - name: Deploy to S3
        run: |
          aws s3 sync ./app/dist/ s3://dreamsync-app-ilona --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1' 
  

    
